FROM python:3.9

WORKDIR /app

COPY ./back/requirements.txt .
COPY ./.env .
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./back/app/ .

CMD ["uvicorn", "app.routing:app", "--reload", "--host", "0.0.0.0", "--port", "80"]