version: '3'
services:
  back:
    build: 
      context: .
      dockerfile: dockerfile.back
    container_name: custom_news_back
    volumes:
      - ./back:/app
    ports:
      - "8080:80"
    env_file:
      - ./back/.env
    depends_on:
      - db

  front:
    build:
      context: ./
      dockerfile: dockerfile.front
    container_name: custom_news_front
    volumes:
      -  ./front:/app
    command: npm start
    ports:
      -  "3000:3000"
    stdin_open: true
    
  
  db:
    container_name: custom_news_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: custom_news
    volumes:
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
