FROM python:3.9

WORKDIR /app

COPY ./back/requirements.txt .
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
RUN apt update
RUN apt-get install -y build-essential libssl-dev libffi-dev python3-dev

CMD ["uvicorn", "app.routing:app", "--reload", "--host", "0.0.0.0", "--port", "80"]